[tox]
envlist = py310, py311, py312, py313, py314
isolated_build = True
ignore_missing_interpreters = True

[testenv]
deps =
  pytest
commands =
  pytest

[testenv:connectivity]
description = one ping per operating system / GH os.runner
commands = pytest tests/test_pubchem_connectivity.py
deps =
  pytest
  {[testenv]deps}
